version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
    networks:
      - web

  ollama:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama
    restart: always
    ports:
      - 3000:8080
    networks:
      - web
    depends_on:
      - traefik
  
  vps:
    build: .
    privileged: true
    ports:
      - "2222:22"
      - "2375:2375"
    volumes:
      - ./data:/root
      - conda-envs:/anaconda/envs
      - ollama:/usr/local/bin
      - /var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]

volumes:
  conda-envs:
  ollama:

networks:
  web:
    external: true