[http.middlewares.simpleAuth.basicAuth]
  users = [
    "ujstor:$apr1$A7LbmVA7$OLsoACiJSHMOirdQeiClE."
  ]

[http.routers.api]
  rule = "Host(`monitor.ujstor.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

[http.services.ollama.loadBalancer]
  [[http.services.ollama.loadBalancer.servers]]
    url = "http://host.docker.internal:3000"

[http.routers.ollama]
  rule = "Host(`ollama.ujstor.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "ollama"
  [http.routers.ollama.tls]
    certResolver = "lets-encrypt"

[http.services.diffusion.loadBalancer]
  [[http.services.diffusion.loadBalancer.servers]]
    url = "http://host.docker.internal:7860"

[http.routers.diffusion]
  rule = "Host(`diffusion.ujstor.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "diffusion"
  [http.routers.diffusion.tls]
    certResolver = "lets-encrypt"

[http.services.fooocus.loadBalancer]
  [[http.services.fooocus.loadBalancer.servers]]
    url = "http://192.168.2.115:7866" #use host ip

[http.routers.fooocus]
  rule = "Host(`fooocus.ujstor.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "fooocus"
  [http.routers.fooocus.tls]
    certResolver = "lets-encrypt"